# Generated by Django 5.1.4 on 2024-12-07 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_livro_capa"),
    ]

    operations = [
        migrations.AddField(
            model_name="autor",
            name="email",
            field=models.CharField(default="teste@teste.com", max_length=100),
            preserve_default=False,
        ),
    ]
